name: Creating a workflow for udemy
on: push

jobs:
    Installing-dependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out code
              uses: actions/checkout@v3

            - name: Installing Node
              uses: actions/setup-node@v3
              with:
                  node-version: 18
            
            - name: Installing dependencies
              run: npm ci
              
    Tests:
        runs-on: ubuntu-latest
        needs: [Installing-dependencies]
        steps:
            - name: Running lint tests
              run: |
                echo "running Lint tests"
                npm lint

            - name: Running "Test" tests
              run: |
                echo "running Test tests"
                npm test

            - name: Running "Build" tests
              run: |
                echo "running Build tests"
                npm build